# Generated by Django 5.0.3 on 2024-05-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_stage_user_remove_subject_user_stage_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='ссылка на видео'),
        ),
    ]
